language: php

php:
  - 5.6
  - 5.5
  - 5.4

services:
  - mysql

before_script:
  # Repositories.
  # @todo, Commit upstream to containers.
  - sudo apt-add-repository 'deb http://us.archive.ubuntu.com/ubuntu/ precise multiverse'
  - sudo apt-add-repository 'deb http://us.archive.ubuntu.com/ubuntu/ precise-updates multiverse'
  - sudo apt-get update

  # Permissions.
  # @todo, Commit upstream to containers.
  - CURRENT_USER=$(whoami)
  - sudo chown -R ${CURRENT_USER}:${CURRENT_USER} $(pwd)

  # Directory stucture.
  - mkdir build

  # Additional PHP config
  - echo -e "apc.enable_cli = 1\napc.shm_size = 128M\napc.num_files_hint = 7000" > apc.ini
  - if [ `expr "$(phpenv global)" "<" "5.5"` -eq 1 ]; then phpenv config-add apc.ini; fi
  - phpenv config-add core/misc/travis-ci/php.ini
  - phpenv config-rm xdebug.ini

  # Apache.
  - sudo apt-get install -y sudo apache2 libapache2-mod-fastcgi
  - sudo a2enmod rewrite actions fastcgi alias

  # FPM.
  - cp $HOME/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default $HOME/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo sed -e "s/;error_log/error_log/g" --in-place $HOME/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo sed -e "s/;log_level/log_level/g" --in-place $HOME/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  # We are running some exec's in our code base. We need to fix fpm's PATH for it to work with phpenv.
  - echo "env[PATH] = $PATH" >> $HOME/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - $HOME/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

  # vHost.
  - sudo cp -f core/misc/travis-ci/vhost.conf /etc/apache2/sites-enabled/000-default
  - sudo sed -e "s?%BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-enabled/000-default

  # Kick Apache!
  - sudo service apache2 restart

  # Mysql.
  - mysql -uroot -proot -hmysql -e 'SET GLOBAL wait_timeout = 5400;'
  - mysql -uroot -proot -hmysql -e 'SET GLOBAL innodb_fast_shutdown=0;'
  - mysql -uroot -proot -hmysql -e 'CREATE DATABASE drupal;'
  - mysql -uroot -proot -hmysql -e 'GRANT ALL PRIVILEGES ON drupal.* TO "drupal"@"%" IDENTIFIED BY "drupal";'
  - mysql -uroot -proot -hmysql -e 'FLUSH PRIVILEGES;'

script:
  - php core/scripts/run-tests.sh --keep-results --color --concurrency 4 --php `which php` --url http://localhost/ --sqlite build/test.sqlite --dburl mysql://drupal:drupal@mysql/drupal --all
